### ISSUE TITLE
Accessing Response Headers

### ISSUE THREAD

**Issue by PaulBullivant** [viagogo/HalKit#21]
Would it be possible to access response headers from the Resource  returned by the call to GetAsync()?
(Or maybe access to the underlying `HttpResponse ` object or the `IApiResponse` created by HalKit?

In particular, I'm looking for ETAGs in the response header so that I can cache resources that don't change often.

(I'm using HalKit for consuming this API which recommends the use of ETAGs):
[(https://api.foxycart.com/docs)]

**Comment by akilb** [comment]
Hi @PaulBullivant,

You can use the `IHttpConnection.SendRequestAsync<T>` (see [here](https://github.com/viagogo/HalKit/blob/master/src/HalKit/Http/IHttpConnection.cs)) method to make the same request as `GetAsync` and return an `IApiResponse<T>`. 

Alternatively, HalKit is designed so you can plug any middleware you want into it. You can add an `DelegatingHandler` that adds any functionality you want into `HttpConnection`. Here's an example of how you could plug in the HTTP caching library [CacheCow](https://github.com/aliostad/CacheCow):

```
var httpConnectionWithCaching = new HttpConnection(new[] {new CacheCow.Client.CachingHandler()}, configuration);
var halClient = new HalClient(configuration, httpConnectionWithCaching);
```

Hope this helps. I'll get the wiki updated with an example of using middleware

**Comment by PaulBullivant** [comment]
Thanks @akilb.  Use of SendRequestAsync<T> looks easy enough.  I'll have to do some training on the DelegatingHandler which I don't fully understand but that does sound like a sensible approach.

**Comment by PaulBullivant** [comment]
I read this and delegate handles makes more sense now. 
http://www.asp.net/web-api/overview/advanced/http-message-handlers

Something like CacheCow looks ideal for my requirements. Thanks again!

**Comment by PaulBullivant** [comment]
Hiya, I'm trying to use IHttpConnection.SendRequestAsync but finding it difficult to use.  I need to pass it an APIRequest but that needs a URI and your LinkResolver instance is buried inside HalClient as a private member.  I don't really want to have to greate a delegate handler when all I want is the IApiResponse.

Do you have any suggestions?

**Comment by PaulBullivant** [comment]
I did this in the end:

```
ApiRequest request = new ApiRequest();
request.Uri = new Uri(link.HRef);
request.Body = myData;
request.Method = HttpMethod.Post;

IApiResponse<T> response = await apiClient.HttpConnection.SendRequestAsync<T>(request, CancellationToken.None);
```

This seems to have done the trick.
